language: d-2.085.0
script: make
before_deploy:
- echo -e "Host digitalmars.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_beb33a8b4591_key -iv $encrypted_beb33a8b4591_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- chmod -R g+w ./out
deploy:
- provider: script
  skip_cleanup: true
  # Travis supports only "one" script deployment
  # The chmod is done separately as it will fail for folder & files not owned by travis_ci_dconf
  script: make deploy
  on:
    branch: master
